### ISSUE TITLE
Reporting 22.10.2024

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/nfdi_search_engine#17]
- [x] Tags/types definitions. NFDI4BIOIMAGE/training#185
- [x] Did you check the docker #2 ?
- [x]  Is the currently version with the github_auto_add, is that the one you want？NFDI4BIOIMAGE/training#246
- [x] Latest Version of the search engine.
- [x] Latest Version of the submit pages.
- [x] How often should docker be told to fetch the latest database?
- [x] Problem with the search range. #15 
- [x] Is it not necessary to add these comments to make them easier to find later, for example in a year's time?NFDI4BIOIMAGE/training#294

**Comment by SeverusYixin** [comment]
Type: the types of the content that it should belong to\
Tags: The key words/exactly thing about/in the content

**Comment by SeverusYixin** [comment]
possible: Everyday get the latest data resource version
