### ISSUE TITLE
Next time report

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/nfdi_search_engine#37]
- [x] Wordcloud on home page #30  #29
- [x] Alphabetical filter for the filter card #33 
- [x] Rewrite the readme with the latest version #34 #38
- [x] Update the filter list order #35  
- [x] Refresh the filter box size after each new search #36
